version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - app-network

  laravel-api:
    build:
      context: .
      dockerfile: Dockerfile   # dùng Dockerfile chuẩn, không còn api.docker
    depends_on:
      - mariadb
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    expose:
      - "8091"   # expose nội bộ cho newman gọi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
